const companies = [
  {
    id: "salesforce",
    name: "Salesforce",
    program: "Associate Product Manager Intern",
    domain: "salesforce.com",
    expectedOpening: "June - July",
    sortMonth: 6,
    signals: "Futureforce talent community",
    link: "https://www.salesforce.com/company/careers/university-recruiting/",
    status: "Not yet open",
    lastChecked: new Date().toISOString()
  },
  {
    id: "meta",
    name: "Meta",
    program: "RPM / Product Management Intern",
    domain: "meta.com",
    expectedOpening: "Late August",
    sortMonth: 8,
    signals: "Meta University (for underclassmen)",
    link: "https://www.metacareers.com/jobs/",
    status: "Not yet open",
    lastChecked: new Date().toISOString()
  },
  {
    id: "amazon",
    name: "Amazon",
    program: "Product Manager – Technical Intern",
    domain: "amazon.com",
    expectedOpening: "August",
    sortMonth: 8.1,
    signals: "Handshake postings, Student Programs portal",
    link: "https://www.amazon.jobs/en/landing_pages/student-programs",
    status: "Not yet open",
    lastChecked: new Date().toISOString()
  },
  {
    id: "apple",
    name: "Apple",
    program: "Product Management / EPM Intern",
    domain: "apple.com",
    expectedOpening: "August - September",
    sortMonth: 8.5,
    signals: "Apple Talent Community",
    link: "https://jobs.apple.com/en-us/search?search=Intern",
    status: "Not yet open",
    lastChecked: new Date().toISOString()
  },
  {
    id: "microsoft",
    name: "Microsoft",
    program: "Product Management Intern",
    domain: "microsoft.com",
    expectedOpening: "August - September",
    sortMonth: 8.6,
    signals: "Microsoft Student Partners",
    link: "https://jobs.careers.microsoft.com/global/en/students",
    status: "Not yet open",
    lastChecked: new Date().toISOString()
  },
  {
    id: "uber",
    name: "Uber",
    program: "Associate Product Manager Intern",
    domain: "uber.com",
    expectedOpening: "August - September",
    sortMonth: 8.7,
    signals: "UberSTAR program",
    link: "https://www.uber.com/us/en/careers/",
    status: "Not yet open",
    lastChecked: new Date().toISOString()
  },
  {
    id: "linkedin",
    name: "LinkedIn",
    program: "Product Management Intern",
    domain: "linkedin.com",
    expectedOpening: "August - September",
    sortMonth: 8.8,
    signals: "LinkedIn Job Alerts",
    link: "https://careers.linkedin.com/students",
    status: "Not yet open",
    lastChecked: new Date().toISOString()
  },
  {
    id: "google",
    name: "Google",
    program: "Associate Product Manager Intern",
    domain: "google.com",
    expectedOpening: "September",
    sortMonth: 9,
    signals: "Campus recruiters",
    link: "https://careers.google.com/students/",
    status: "Not yet open",
    lastChecked: new Date().toISOString()
  },
  {
    id: "atlassian",
    name: "Atlassian",
    program: "Associate Product Manager Intern",
    domain: "atlassian.com",
    expectedOpening: "September",
    sortMonth: 9.1,
    signals: "Atlassian Student Talent Community",
    link: "https://www.atlassian.com/company/careers/students",
    status: "Not yet open",
    lastChecked: new Date().toISOString()
  },
  {
    id: "stripe",
    name: "Stripe",
    program: "Product Manager Intern",
    domain: "stripe.com",
    expectedOpening: "September",
    sortMonth: 9.2,
    signals: "Direct application (highly selective)",
    link: "https://stripe.com/jobs/",
    status: "Not yet open",
    lastChecked: new Date().toISOString()
  },
  {
    id: "adobe",
    name: "Adobe",
    program: "Product Management Intern",
    domain: "adobe.com",
    expectedOpening: "Late August - Early September",
    sortMonth: 8.8,
    signals: "Adobe Intern Legacy events",
    link: "https://www.adobe.com/careers.html",
    status: "Not yet open",
    lastChecked: new Date().toISOString()
  },
  {
    id: "intuit",
    name: "Intuit",
    program: "Product Management Intern",
    domain: "intuit.com",
    expectedOpening: "Late Summer - Early Fall",
    sortMonth: 8.9,
    signals: "Intuit careers job alerts",
    link: "https://www.intuit.com/careers/",
    status: "Not yet open",
    lastChecked: new Date().toISOString()
  },
  {
    id: "capitalone",
    name: "Capital One",
    program: "Product Management Intern",
    domain: "capitalone.com",
    expectedOpening: "July - August",
    sortMonth: 7.5,
    signals: "Virtual Summits (June/July)",
    link: "https://www.capitalonecareers.com/",
    status: "Not yet open",
    lastChecked: new Date().toISOString()
  },
  {
    id: "spotify",
    name: "Spotify",
    program: "Product Management Intern",
    domain: "spotify.com",
    expectedOpening: "August - November",
    sortMonth: 8.5,
    signals: "Spotify Students page",
    link: "https://www.lifeatspotify.com/students",
    status: "Not yet open",
    lastChecked: new Date().toISOString()
  },
  {
    id: "dropbox",
    name: "Dropbox",
    program: "Product Management Intern",
    domain: "dropbox.com",
    expectedOpening: "August - September",
    sortMonth: 8.4,
    signals: "Dropbox Talent Community",
    link: "https://jobs.dropbox.com/",
    status: "Not yet open",
    lastChecked: new Date().toISOString()
  },
  {
    id: "tiktok",
    name: "TikTok",
    program: "Product Management Intern",
    domain: "tiktok.com",
    expectedOpening: "Rolling (Jan-Jun & Jul-Dec)",
    sortMonth: 7,
    signals: "Frequent checking required",
    link: "https://careers.tiktok.com/",
    status: "Not yet open",
    lastChecked: new Date().toISOString()
  },
  {
    id: "doordash",
    name: "DoorDash",
    program: "Product Management Intern",
    domain: "doordash.com",
    expectedOpening: "August - October",
    sortMonth: 8.2,
    signals: "DoorDash University Careers",
    link: "https://doordash.jobs/university/",
    status: "Not yet open",
    lastChecked: new Date().toISOString()
  },
  {
    id: "pinterest",
    name: "Pinterest",
    program: "Product Management Intern",
    domain: "pinterest.com",
    expectedOpening: "August - September",
    sortMonth: 8.3,
    signals: "Pinterest careers alerts",
    link: "https://www.pinterestcareers.com/",
    status: "Not yet open",
    lastChecked: new Date().toISOString()
  },
  {
    id: "lyft",
    name: "Lyft",
    program: "Product Management Intern",
    domain: "lyft.com",
    expectedOpening: "August - September",
    sortMonth: 8.4,
    signals: "Early Talent portal",
    link: "https://www.lyft.com/careers",
    status: "Not yet open",
    lastChecked: new Date().toISOString()
  },
  {
    id: "snowflake",
    name: "Snowflake",
    program: "Product Management Intern",
    domain: "snowflake.com",
    expectedOpening: "July - October",
    sortMonth: 7.8,
    signals: "Snowflake Talent Community",
    link: "https://careers.snowflake.com/",
    status: "Not yet open",
    lastChecked: new Date().toISOString()
  }
];
